import { Inter } from 'next/font/google'
import { Banner, Header, Navbar, ProductFeed } from '../components'

import Head from 'next/head'

interface Props {
  products: Product[]
}
export default function Home({ products }: Props) {

  return (
    <>
      <Head>
        <title>Myntra-At</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-100'>
        <Navbar />

        <Header />

        <main className='h-[20rem]'>
          <Banner />

          <ProductFeed products={products} />
        </main>

      </div>
    </>
  )
}

export async function getServerSideProps(context: any) {
  const response = await fetch('https://api.escuelajs.co/api/v1/products?offset=0&limit=30')
  const products = await response.json()
  return {
    props: {
      products
    }
  }
} 